Staffstaff:
    resource: "@TrombinoscopeStaffBundle/Resources/config/routing.yml"
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

login:
    pattern:   /login
    defaults:  { _controller: TrombinoscopeStaffBundle:Security:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout

