Staffstaff_homepage:
    path:     /
    defaults: { _controller: StaffstaffBundle:Default:index }

Staffstaff_personne:
    path:    /Personnes/index
    defaults: {_controller:StaffstaffBundle:Personnes:index}
Staffstaff_service:
    path:    /Services/index/
    defaults: {_controller:StaffstaffBundle:Services:index}